<?php

  function cipher_menu() {
    $items['cipher'] = array(
      'title' => 'Cipher',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('cipher_form'),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
    );
    $items['cipher_success'] = array(
      'title' => 'Your Results:',
      'page callback' => 'cipher_results',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );
    return $items;
  };

  function cipher_form() {
    $form['phrase'] = array(
      '#title' => 'Phrase',
      '#type' => 'textfield',
      '#description' => t('Add a word or phrase you would like to encrypt'),
    );
    $form['value'] = array(
      '#title' => 'Shift Value',
      '#type' => 'textfield',
      '#description' => t('How many spaces in the alphabet would you like each letter to shift?'),
    );
    $form['direction'] = array(
      '#title' => 'Shift Direction',
      '#type' => 'textfield',
      '#description' => t('Which direction in the alphabet would you like each letter to shift?'),
    );
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Encrypt!',
    );
    return $form;
  }

  function cipher_form_submit($form, &$form_state) {
    $phrase = $form_state['values']['phrase'];
    $value = $form_state['values']['value'];
    $direction = $form_state['values']['direction'];

    $alpha_array = array('a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z');
    $ciphered_array = array();


    $phrase_to_lower = strtolower($phrase);
    $phrase_split = str_split($phrase_to_lower);

    for ($i=0; $i < sizeof($phrase_split); $i++) {
      if (in_array($phrase_split[$i], $alpha_array)) {
        for ($x=0; $x < sizeof($alpha_array); $x++) {
          if ($phrase_split[$i] == $alpha_array[$x]) {
            array_push($ciphered_array, $alpha_array[$x + $value]);
          }
        }
      } else {
        array_push($ciphered_array, $phrase_split[$i]);
      }
    }
    $ciphered_string = implode('', $ciphered_array);


    $_SESSION['var_test'] = $phrase_split;

    $_SESSION['phrase'] = $phrase;
    $_SESSION['value'] = $value;
    $_SESSION['direction'] = $direction;
    $_SESSION['output'] = $ciphered_string;
    $form_state['redirect'] = 'cipher_success';
  }

  function cipher_results() {
    $phrase = $_SESSION['phrase'];
    $value = $_SESSION['value'];
    $direction = $_SESSION['direction'];
    $output = $_SESSION['output'];

    $var_test = $_SESSION['var_test'];
    var_dump($var_test);
    return
      '<p>Your input phrase is <strong>' . $phrase .
      '</strong>, the shift value you entered is <strong>' . $value .
      '</strong> and the shift direction you entered is <strong>' . $direction .
      '</strong>. Here is your encrypted phrase:<br>' . $output .
      '</p>';
  }
